import React from 'react';
import Head from 'next/head';
import { Main } from '@/styles/styledComponents';


export default function Home() {

  return (
    <>
      <Head>
        <title>Rent VHS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
      </Main>
    </>
  );
}
